[2024-05-03T11:31:00.754+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:31:00.820+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-10T01:00:00+00:00 [queued]>
[2024-05-03T11:31:00.837+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-10T01:00:00+00:00 [queued]>
[2024-05-03T11:31:00.838+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-03T11:31:00.856+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-10 01:00:00+00:00
[2024-05-03T11:31:00.864+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=195) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:31:00.866+0000] {standard_task_runner.py:63} INFO - Started process 200 to run task
[2024-05-03T11:31:00.863+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-10T01:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmph2dwt1cn']
[2024-05-03T11:31:00.867+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask extract_data_from_api
[2024-05-03T11:31:00.909+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:31:01.078+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-10T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:31:01.225+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-10T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-10T01:00:00+00:00'
[2024-05-03T11:31:01.227+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:31:01.241+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:31:01.243+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-10","date":"2022-08-10"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:31:01.254+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:31:01.268+0000] {subprocess.py:93} INFO - Request failed with status code 000
[2024-05-03T11:31:01.269+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-03T11:31:01.270+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:31:01.283+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03T11:31:01.289+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220810T010000, start_date=20240503T113100, end_date=20240503T113101
[2024-05-03T11:31:01.304+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task extract_data_from_api (Bash command failed. The command returned a non-zero exit code 1.; 200)
[2024-05-03T11:31:01.328+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T11:31:01.355+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:31:01.359+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-03T11:32:30.800+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:32:30.839+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-10T01:00:00+00:00 [queued]>
[2024-05-03T11:32:30.854+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-10T01:00:00+00:00 [queued]>
[2024-05-03T11:32:30.855+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-03T11:32:30.923+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): extract_data_from_api> on 2022-08-10 01:00:00+00:00
[2024-05-03T11:32:30.932+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=260) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T11:32:30.933+0000] {standard_task_runner.py:63} INFO - Started process 268 to run task
[2024-05-03T11:32:30.931+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'extract_data_from_api', 'scheduled__2022-08-10T01:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmplpan2w_x']
[2024-05-03T11:32:30.934+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask extract_data_from_api
[2024-05-03T11:32:30.949+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-03T11:32:30.993+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-10T01:00:00+00:00 [running]> on host 5137b2b1dc87
[2024-05-03T11:32:31.089+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2022-08-10T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-10T01:00:00+00:00'
[2024-05-03T11:32:31.089+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:32:31.107+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:32:31.108+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "http://host.docker.internal:8081/sales" -H "Content-Type: application/json" -d \'{"raw_dir":"file_storage/raw/sales/2022-08-10","date":"2022-08-10"}\')\n    if [ $response -ne 201 ]; then\n        echo "Request failed with status code $response"\n        exit 1\n    fi\n    ']
[2024-05-03T11:32:31.117+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T11:32:31.129+0000] {subprocess.py:93} INFO - Request failed with status code 000
[2024-05-03T11:32:31.130+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-03T11:32:31.131+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:32:31.142+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03T11:32:31.146+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=process_sales, task_id=extract_data_from_api, execution_date=20220810T010000, start_date=20240503T113230, end_date=20240503T113231
[2024-05-03T11:32:31.159+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task extract_data_from_api (Bash command failed. The command returned a non-zero exit code 1.; 268)
[2024-05-03T11:32:31.187+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T11:32:31.211+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:32:31.213+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
